### PR TITLE
Some changes

### PR DESCRIPTION
**Pull request by carloscarcamo**
- Bug #20 fixed
- Allow to search multiple keywords, see #18

I hope this helps :)

### CODE REVIEW

**Comment by carloscarcamo** [comment]
sorry, I made a typo on a commit description


> new deps:
> - promise (this probably will be necessary when using ES6)

- promise (this probably will be unnecessary when using ES6)

> - validator

**Comment by anvk** [comment]
Looks great! By the way try to use `git rebase` next time to fix "bad" commit descriptions. Also I think it will be good if we fix/squash commits into 1 when submit a pull request since this way it is easier to roll back if something went wrong. But I'm going to merge it anyway.

**Comment by carloscarcamo** [comment]
Ok. I will be more careful next time and will be waiting for more updates and see in what else can I contribute :)

**Comment by anvk** [comment]
@carloscarcamo I merged my changes which move this project to webpack and ES6 (latest JavaScript). I think my next step is to move it to Redux from Flux but it should not effect things much at this point. Are you still interested in contributing? I have a list of things I can assign to you - some of them should be simple (I hope).

**Comment by carloscarcamo** [comment]
I very interested in contributing, you can assign me some task and I will try to help :)
By the way, I would like to know from where or how do you get the Tweets database, is there any project which collect those tweets?

**Comment by carloscarcamo** [comment]
@anvk I'm very interested in contributing, you can assign me some tasks and I will try to help :)
By the way, I would like to know from where or how do you get the Tweets database, is there any project which collect those tweets?

**Comment by anvk** [comment]
@carloscarcamo here is a tiny issue if you want to help https://github.com/JaredHawkins/TweetGeoViz/issues/50 
Also you can try to build the page on your computer and let me know if it worked for you.

I was thinking to have a meeting next week in Slack to discuss our next step for the project development. Are you interested to join?

To answer your question: just like it is mentioned in the README file, this tweets sample is courtesy of HealthMap. @JaredHawkins who is the brain behind this project has access to HealthMap tweets, so he managed to get a sample set we can work with. But in theory you could create the data set yourself using any data from any sources you have.

**Comment by carloscarcamo** [comment]
@anvk, yes I'm interested to join in the Slack discussion, just tell me the day and hour :)

I asked about the tweets db because, we would like to use this project in another one to collect information about the use of open source projects around the world.

**Comment by JaredHawkins** [comment]
Hi all,

My apologies on the delay - I have been out of town at a conference and have had limited email access.

So glad this project is moving along.  Thanks for your interest Carlos!  I would be happy to chat.  I can be available asynchronously on Slack this week, but if you want a dedicated time next week will be better.  

As for the Tweets, I run about a dozen or so research projects using Twitter data here @ Boston Children’s Hospital.  Everything is obtained via the free public API.  The Tweets in this sample database are explicitly for this Mozilla project, however, and should not be used/referenced in any other projects.

Thanks!

-Jared

**Comment by anvk** [comment]
@JaredHawkins 
no problem. Right now we have a plan to iron out some of the known bugs and add newest tech to the project before we move along with new features. I think that next week will be better for me as well. If @carloscarcamo is avail too we can chat next week about our next steps.

**Comment by carloscarcamo** [comment]
I think I will have time, just tell me the day and hour...

**Pull request merged**
