### PR TITLE
issue50: Fixing some warnings during npm install

### PR DESCRIPTION
**Pull request by carloscarcamo**
- Using the correct apache licence identifier in ```package.json```, see: https://spdx.org/licenses/
- ```gulp-clean``` deprecated in favor of ```del```, see [here](https://github.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md#delete-files-and-folders)
- Update dependencies using caret(^) in version
- (Bonus) adding dependency badges from https://david-dm.org/

### CODE REVIEW

**Comment by carloscarcamo** [comment]
I made a mess with the previous pull request so I'm sending another one...

**Comment by anvk** [comment]
Just like my previous comment - you need to bump project version. Actually for every merge request - we need to bump the last number (x.y.z so we need to bump z). This way every single change to the project will have its own number so you always know if the version of the app you are currently working is the latest or not. Bump the version number and I will merge.

**Comment by carloscarcamo** [comment]
Done...

**Comment by anvk** [comment]
Merged! Thanks for contributing!

**Pull request merged**
